### ISSUE TITLE
Node#before is deprecated. Use Node#raws.before

### ISSUE THREAD

**Issue by francoisromain** [MoOx/postcss-cssnext#387] opened 2017-05-19 01:41 UTC
Hello 
When I use `postcss-import` and then `postcss-next`, there is this warning in the console: 

`Node#before is deprecated. Use Node#raws.before`

I made a repo to reproduce here: 
https://github.com/francoisromain/test-postcss-import-cssnext

**Comment by wbyoung** [comment] 2017-05-23 18:42
This is likely a duplicate of #374.

**Closed** 2017-05-23 18:45 UTC
