### ISSUE TITLE
Remove some `not future css` plugins from next major release

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#375] opened 2017-05-07 10:48 UTC
1. [postcss-color-rgba-fallback](https://github.com/postcss/postcss-color-rgba-fallback)
`rgba(153, 221, 153, 0.8)` -> `#99DD99`
http://caniuse.com/#feat=css3-colors (IE 8-)

2. [postcss-pseudoelements](https://github.com/axa-ch/postcss-pseudoelements)
`:before {}` -> `::before {}`
http://caniuse.com/#feat=css-gencontent (IE 8-)

3. [pixrem](https://github.com/robwierzbowski/node-pixrem)
`2.5rem` -> `80px`
http://caniuse.com/#feat=rem (IE 10-)

Good plugin pack for this plugins: https://github.com/jonathantneal/oldie

**Comment by MoOx** [comment] 2017-05-09 04:34
Why not. Curious to know what people want.

https://twitter.com/cssnext/status/861801417719382016

**Comment by jonathantneal** [comment] 2017-05-10 20:07
I did not get to participate in this poll, but I would have voted in favor of removing these not future css plugins. Congrats on getting so many participants. It looks like a large majority wanted them gone.

**Comment by jonathantneal** [comment] 2017-05-11 00:33
Also, you might want to remove pleeease-filters from https://github.com/MoOx/postcss-cssnext/issues/374#issuecomment-299646636. Firefox has supported gradients since early 2015 in version 35 (we are on 53).

From the pleeease-filters docs:

> Firefox support SVG filters (and CSS shorthand since FF35)

Confirmed by [caniuse](http://caniuse.com/#feat=css-filters).

**Comment by Semigradsky** [comment] 2017-05-11 06:40
> Firefox has supported gradients since early 2015 in version 35 (we are on 53).

How about IE 11 support?

**Comment by timkelty** [comment] 2017-05-12 14:31
The future of `@apply` is also not looking so good: http://www.xanthir.com/b4o00
I'd consider removing `postcss-apply`.

**Comment by jonathantneal** [comment] 2017-05-12 19:09
I’ve pinged the csswg or anyone who can spare time to update this db with accurate information.

https://twitter.com/jon_neal/status/863108278666047488

If we get that repo in order as a source of truth, we can very intelligently update the feature set in cssnext, and even add stages/env in the future.

**Comment by jonathantneal** [comment] 2017-05-17 23:30
> How about IE 11 support?

IE does not support SVGs filters.

**Comment by Kovensky** [comment] 2017-10-12 02:41
I'd also suggest removing `color` from postcss-cssnext. Supporting the current `css-color-function` plugin not only (incorrectly) implements a spec that is considered dead by its author, but also prevents adding support for a possible real transform for the actual `color` function.

See comments by tabatkins on https://github.com/ianstormtaylor/css-color-function/pull/35.

**Comment by jonathantneal** [comment] 2017-10-12 14:59
If the name is locked to `color-mod` so that it matches the current spec, then I don’t see a problem in keeping it around.

**Comment by jonathantneal** [comment] 2018-05-04 13:12
Possibly resolved by #445

**Comment by MoOx** [comment] 2018-05-29 07:51
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/

**Closed by MoOx** 2018-05-29 07:51 UTC
Labels: status: discussion
