### ISSUE TITLE
:matches(element)

### ISSUE THREAD

**Issue by stevenvachon** [MoOx/postcss-cssnext#287] opened 2016-06-15 20:17 UTC
```css
.class {
  &:matches(element) {
    property: value;
  }
}
```
produces:
```css
.classelement {
  property: value;
}
```
when it *should* produce:
```css
element.class {
  property: value;
}
```

**Comment by MoOx** [comment] 2016-06-16 03:25
Looks like a bug indeed. Feel free to report it here https://github.com/postcss/postcss-selector-matches.
PR welcome!

**Comment by MoOx** [comment] 2016-09-06 05:38
Closed by https://github.com/postcss/postcss-selector-matches/pull/8

**Comment by yordis** [comment] 2016-09-06 05:39
@MoOx Can you update the release on the other package I want to add some regression testing in this package

**Closed by MoOx** 2016-09-06 05:38 UTC
Labels: type: bug

**Comment by MoOx** [comment] 2016-09-06 05:40
No need to do it. No need to duplicate a test ;)

**Comment by yordis** [comment] 2016-09-06 05:41
@MoOx isn't duplicate testing. Remember that we created the regression testing for see how it works with every feature enabled

**Comment by MoOx** [comment] 2016-09-06 05:44
cssnext don't cover all possibilities of packages used. And I guess most packages don't cover all use case of they libraries they used...

**Comment by yordis** [comment] 2016-09-06 05:45
@MoOx that's why we could use this regression for check that IMO

**Comment by yordis** [comment] 2016-09-06 05:48
@MoOx will you create a release for this fix? I need this feature.

**Comment by MoOx** [comment] 2016-09-06 05:59
We don't need a release for this fix. Our current usage of [postcss-selector-matches](https://github.com/MoOx/postcss-cssnext/blob/4717a5963144c7292e3dc5d73c3c7dfe58ba0be4/package.json#L49) will get all patch release automatically. postcss-selector-matches 2.0.2 is out, so just reinstall postcss-cssnext and it should be good for you.
