### ISSUE TITLE
Unable to Parse Variable in Color Function

### ISSUE THREAD

**Issue by realph** [MoOx/postcss-cssnext#260] opened 2016-02-03 14:45 UTC
For some reason, as of a recent update I'm unable to put a variable inside the color function. This used to work:

    `.text {
        color: color(var(--mainColor) lightness(+10%));
    }`

No it's throwing up this error:

>Warning: Running "cssnext:dist" (cssnext) task
    Warning: <css input>:22:26: Unable to parse color from string "var(--mainColor)" Use --force to continue.

Any idea why this is causing this error? Any help is appreciated. Thanks in advance!

**Comment by MoOx** [comment] 2016-02-03 14:51
```
:root {
  --mainColor: #aaa
}

.text {
  color: color(var(--mainColor) lightness(+10%));
}
```

This snippet works on the playground.
It seems your definition is missing, so the var() is not transformed correctly.
If your definition is in another file, take a look to own you import it.

Is this working?

```
.text {
  color: var(--mainColor);
}
```

What is your full postcss config?

**Comment by MoOx** [comment] 2016-03-12 05:36
Closing due to the lack of information.

**Closed by MoOx** 2016-03-12 05:36 UTC

**Comment by steverandy** [comment] 2016-07-21 16:23
I'm having a similar problem with the latest version 2.7.0.

`background: color(var(--primary-color) a(50%));` compiles with this error: `Unable to parse color from string "var(--primary-color)"`

`background: var(--primary-color);` compiles without error

**Comment by steverandy** [comment] 2016-07-22 02:22
I figured out the issue.
It seems because I'm setting `browsers: ["last 2 chrome versions"]`, cssnext disables customProperties feature. Therefore variables aren't parsed.

**Comment by adamgruber** [comment] 2016-09-07 15:11
@steverandy I'm seeing this same issue but it was working previously. Do we know why setting `browsers: [ "last 2 chrome versions" ]` disables `customProperties`?

**Comment by wadehammes** [comment] 2016-09-11 04:31
@adamgruber what was your issue? Having same issue here but can't seem to troubleshoot it.

**Comment by MoOx** [comment] 2016-09-11 07:28
latest versions of chrome support custom props, so automatically disable, so create issue with color(var( (the plugin needs real color).
See here to enable by force a plugin http://cssnext.io/usage/#features

**Comment by wadehammes** [comment] 2016-09-11 12:48
@MoOx setting custom properties to `true` still throws the error (or I am not understanding that doc entry)

**Comment by wadehammes** [comment] 2016-09-11 18:34
@MoOx I'm still getting this error, no matter if I do:

```
require("postcss-cssnext")({
      features: {
        customProperties: {
          preserve: true,
          appendVariables: true
        },
        autoprefixer: false
      }
    })
```

or

```
require("postcss-cssnext")({
      features: {
        customProperties: true,
        autoprefixer: false
      }
    })
```

any help? Can't compile anything currently.

**Comment by MoOx** [comment] 2016-09-11 19:16
Please provide your entire postcss config.

**Comment by wadehammes** [comment] 2016-09-11 19:32
@MoOx 

Currently using this via a Gulp task.
```
gulp.task('stylesheets', function () {
  var processors = [
    require("postcss-import")(),
    require("postcss-url")(),
    require("postcss-cssnext")({
      features: {
        customProperties: {
          preserve: true,
          appendVariables: true
        },
        autoprefixer: false
      }
    }),
    require("cssnano")(),
    require("postcss-browser-reporter")(),
    require("postcss-reporter")()
  ];
  return gulp.src(stylePathSrc)
    .pipe(plumber())
    .pipe( sourcemaps.init() )
    .pipe(postcss(processors))
    .pipe( sourcemaps.write('.') )
    .pipe(gulp.dest(stylePathDest))
    .pipe(browserSync.stream())
    .pipe(notify({ message: 'Styles task complete' }));
});
```

**Comment by MoOx** [comment] 2016-09-11 19:33
Where is defined --sky-blue ? Please also provide more CSS in order to get an accurate help :)

**Comment by wadehammes** [comment] 2016-09-11 19:36
@MoOx 

From buttons.css
```
input[type="submit"]:hover {
  background: color(var(--sky-blue) shade(10%));
}
```

Colors are defined in my root base.css file, which includes all the imports of components like buttons:
```
:root {
  --orange: #FF8500;
  --green: #16DB34;
  --torch-red: #FF1840;
  --route-six: #424242;
  --steady-grey: #E9E9E9;
  --bc: #BCBCBC;
  --sky-blue: #00B8FF;
}
```

**Comment by wadehammes** [comment] 2016-09-11 19:36
@MoOx this was working up until a couple days ago.

**Comment by MoOx** [comment] 2016-09-11 19:38
What did you changed then? Do you have a .browserslistrc or something ?

**Comment by wadehammes** [comment] 2016-09-11 19:40
@MoOx I've changed nothing (besides bumping to version 2.8.0 recently, but was compiling fine after that). I do not have a browserlist file, I think the Chrome inclusion of custom properties is cause of this, but not sure how to correct.

**Comment by wadehammes** [comment] 2016-09-11 19:41
@MoOx this is happening on every project I use this build with too.

**Comment by MoOx** [comment] 2016-09-11 19:44
Can you create a small repo with a repro of this? I don't have much time atm.

**Comment by wadehammes** [comment] 2016-09-11 19:49
@MoOx think I found the issue...just spun up an older repo that was using `gulp-postcss` v6.1.1 and everything is working fine. The issues above are with v6.2.0.

**Comment by wadehammes** [comment] 2016-09-11 19:50
@MoOx Ill go over there and see what's up, thank you!

**Comment by wadehammes** [comment] 2016-09-11 19:53
@MoOx actually, no still throwing an error even when versioning down. So confused as to why this is happening.

**Comment by MoOx** [comment] 2016-09-11 19:54
Please create a minimal reproduction in a repo, that will help to debug.

**Comment by adamgruber** [comment] 2016-09-11 19:57
@wadehammes My issue was user error. I'm using stylelint in my pipeline and had somehow removed my `.stylelintrc` file but once I put it back things worked fine.

**Comment by wadehammes** [comment] 2016-09-11 20:09
@MoOx https://github.com/wadehammes/base-css4

Not necessarily small, but I dont have much time to whip something else up so replicated here in my html starter repo.

**Comment by MoOx** [comment] 2016-09-11 20:13
Can you try postcss-import@^7.0.0 ? v8 sucks so much in many point...
Also, you should use local import path, like `@import './global/import';`.

**Comment by wadehammes** [comment] 2016-09-11 20:14
@moOx although now it works if I remove the `customProperties` features flag entirely. I have it working now in all my projects except one. Ill have to do more poking around and set up a different repo for you. Sorry!

**Comment by MoOx** [comment] 2016-09-11 20:15
I insist, please try postcss-import v7, v8 have a lot of know bugs and that can be the reason in your case...

**Comment by wadehammes** [comment] 2016-09-11 20:16
@moOx that could definitely be it. Trying now!

**Comment by wadehammes** [comment] 2016-09-11 20:30
@MoOx that wasn't the issue either. But, I deleted the output css files out of curiosity and reran the gulp task (in the still broken repo), and it's actually compiling and converting the color appropriately but still throwing the error message...so I'm guess a false error flag?

**Comment by wadehammes** [comment] 2016-09-12 13:41
For those that continue to have this issue, check your task. For our instance, the error lied in how we had our gulp task set up, passing our entire css directory (via `css/**/*.css`) into the task, instead of the file that actually just includes the imports of those. This caused us to have things multi-parsing and throwing the error (although it would still compile fine).

Changing our task to accept just our file with all our css imports in it fixed this for me.

**Comment by gerardo-rodriguez** [comment] 2016-09-29 19:40
Hello, I'm running into this issue as well when I try to set the `customProperties: { preserve: true }` options.

Here's a snippet of what I've got set up:
```js
//gulpfile.js
const postcss = require('gulp-postcss');
const importer = require('postcss-import');
const cssnext = require('postcss-cssnext');

const config = {
  dest: './public',
  css: {
    main: './src/styles/main.css',
    src: './src/styles/**/*.css',
    plugins = [
      importer(),
      cssnext({
        features: {
          customProperties: {
            preserve: true
          }
        }
      })
    ]
  }
};

gulp.task('custom-css-task', () => gulp.src(config.css.main)
  .pipe(postcss(config.css.plugins))
  .pipe(gulp.dest(config.dest))
);
```
The error I get is:
```sh
button.css:67:3: Unable to parse color from string "var(--Button-background-primary)"
```
Here's a snippet from `button.css`:
```css
/* config at top of file */
:root {
  --Button-background-primary: var(--color-primary);
}

/* more button styles... */

.Button--primary:matches(:active, :hover, :focus) {
  /* 67:3 - This line is where the error occurs */
  background-color: color(var(--Button-background-primary) shade(15%));
}
```

The `--color-primary` is set in a `config.css`:
```css
:root {
  --color-primary: var(--color-red);
}
```
For reference, the `main.css` imports both of these:
```css
@import "button.css";
@import "config.css";

* {
  /* some styles */
}
```

If I set the `preserve` value to `false` or `'computed'`, then no errors occur and it compiles fine. The challenge is I need to set the `preserve` value to `true` so that I can later use JS to change the `--color-primary` value on-the-fly so that the button styles can make use of the updated `--color-primary` color.

Does anyone here notice an issue with how I'm attempting to use the `customProperties: { preserve: true }` options? Am I missing something obvious?

Thanks in advance! 😉

**Comment by MoOx** [comment] 2016-09-30 06:30
The color plugin can't just do its job on a non processed value :/

**Comment by gerardo-rodriguez** [comment] 2016-09-30 17:10
@MoOx Of course! Silly me. 😅  I appreciate the response. Thank you!

**Comment by BrianSipple** [comment] 2016-10-22 08:03
I'm having the same issue as @gerardo-rodriguez, but I can't really make out from the discussion what the fix was.

My config (via `broccoli`):

```js
    postcssOptions: {
      compile: {
        enabled: true,
        plugins: [
          { module: cssImport },
          { module: cssColorFunction },
          { module: cssNext }
        ]
      }
    }
```
And then even something basic like this fails:

```css
:root {
  --mainColor: #aaa
}

.text {
  color: color(var(--mainColor) lightness(+10%));
}
```

...the error being `Unable to parse color from string "var(--mainColor)"`

**Comment by jarodtaylor** [comment] 2017-05-05 20:09
I had this same issue until I realized I had used the `color()` function incorrectly. I had a comma between my `var(--)` and the `alpha()`. 

Just in case someone else runs into this!
