### ISSUE TITLE
Bug with nesting

### ISSUE THREAD

**Issue by sc0rp10** [MoOx/postcss-cssnext#389] opened 2017-05-22 10:35 UTC
Hi, I found strange bug that I cannot reproduce in playground.
I have following `foo.css`:
```css
.foo {
    color: #000;
    &__bar {
        color: #aaa;
    }

    &__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
    }
}

```
And next `gulpfile.js`:
```js
const gulp = require("gulp");
const postcss = require("gulp-postcss");

gulp.task('css', function () {
    return gulp.src('foo.css')
        .pipe( postcss([ require('postcss-cssnext') ]) )
        .pipe( gulp.dest('build/') );
});

```
`package.json`:
```json
{
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-postcss": "^7.0.0",
    "postcss-cssnext": "^2.11.0"
  }
}
```
I expect:
```css
.foo {
    color: #000
}
.foo__bar {
    color: #aaa
}
.foo__baz {
    color: #bbb
}
.foo__baz:hover {
    color: #ccc
}
```
But I found:
```css
.foo__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
}.foo {
    color: #000
}

.foo__bar {
        color: #aaa;
}

```

What am I doing wrong?
Can you please help me with the right setup?
Thanks!

**Comment by MoOx** [comment] 2017-05-22 10:35
I think the notation you used is incorrect, per spec. Poke @jonathantneal

**Comment by sc0rp10** [comment] 2017-05-22 10:36
oh, but why playground works as me expected?

**Comment by jonathantneal** [comment] 2017-05-22 13:39
Yes, that notation is incorrect. It is using Sassy combinations, which might be best to transpile using a non-spec plugin like [postcss-nested](https://github.com/postcss/postcss-nested). See https://github.com/jonathantneal/postcss-nesting/issues/17 for further information and commentary from the spec author.

**Comment by mselmany** [comment] 2017-05-22 18:53
Also, some plugins in the cssnext wasnt updated to v6. It causes the problem.
Try install only updated plugins one by one.
Look updated plugins here :   #374

**Comment by daniladaniladanila** [comment] 2017-05-26 09:55
@jonathantneal Thanks for your answer!
But I have the same problem as @sc0rp10. My code has been working for two years, and now it is broken, I can't understand why. 

And if we with @sc0rp10 use wrong notation, why your own Playground works as we expected? 

I updated postcss-nesting manually, but it didn't help

**Comment by skipjack** [comment] 2017-05-26 18:38
I ran into the same issue and thought it was caused by `postcss-nested` however it turned out the issue was with this plugin not being compatible with the latest version of `postcss`. See postcss/postcss-loader#210.

@sc0rp10 if you've updated `postcss-loader` and other plugins, this is likely the cause of the issue. 

I put together a small [demo repo](https://github.com/skipjack/postcss-loader-issue), mentioned in the postcss-loader issue I linked to, if that helps anyone. It seems we should be tracking #374 for a fix for this.

**Comment by peirix** [comment] 2017-06-16 12:48
This bug shows up from time to time even if not using sassy combinations.

```
.icon {
    width: 45px;
    height: 45px;

    & svg {
        stroke: #fff;
    }

    & div {
        border-color: #000;

        & svg {
            stroke: #000;
        }
    }
}
```

This outputs to:

```
.icon div {
        border-color: #000;

        & svg {
            stroke: #000;
        }
}.icon {
    width: 45px;
    height: 45px
}

.icon svg {
        stroke: #fff;
}
```

So as you can see it's both jumbled (as others have described as well), and also not compiling correctly.

Setup:
```
"devDependencies": {
    "gulp": "^*",
    "gulp-postcss": "^7.0.0"
  }
```
```
var gulp			= require("gulp"),
	postcss 		= require('gulp-postcss'),
	cssnext 		= require('postcss-cssnext');

gulp.task('css', function () {
    var plugins = [
        cssnext({browsers: ['last 2 version']})
    ];
    return gulp.src('./*.css')
        .pipe(postcss(plugins))
        .pipe(gulp.dest('./dest'));
});
```

**Comment by gcedo** [comment] 2017-06-20 11:04
It's happening to me too. I updated `postcss-cssnext` during a migration to Webpack 2 to `2.11.0`, then I had to downgrade it to `2.9.0` because of #357.

Then both `nesting` and `apply` plugins were not working properly anymore. More specifically, `nesting` would not work if the nesting level was deeper than one, as reported in react-boilerplate/react-boilerplate#853, whereas `apply` would simply not work.

I managed to fix this issue with the following packages and postcss setup:

```json
    "postcss-apply": "^0.8.0",
    "postcss-cli": "^4.1.0",
    "postcss-cssnext": "2.9.0",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-nesting": "^4.0.1",
```

```js
const path = require('path');

module.exports = {
  loader: 'postcss-loader',
  options: {
    plugins: () => [
      require('postcss-import')({
        path: [path.resolve(__dirname, '../../src/css')],
      }),
      require('postcss-apply')(),
      require('postcss-cssnext')(),
      require('postcss-nesting')(),
    ],
  },
};

```

**Comment by donaldshen** [comment] 2017-07-04 15:49
I have this issue:
```
.swiper-slide {
    background-color: white;

    & > img {
        height: 100%;
    }

    & > div {
        padding: 2rem 1rem;

    }
}
```
compile with gulp-postcss & postcss-cssnext:
```
.swiper-slide {
    background-color: white
}

.swiper-slide > img {
        height: 100%;
}
```
It can only compile the first & block. Btw, it's ok with playground.

**Comment by MoOx** [comment] 2017-07-05 20:14
Hopefully update of deps in #400 will fix this.

**Closed** 2017-07-05 20:25 UTC

**Comment by jdinartejesus** [comment] 2017-07-06 08:12
@MoOx I updated to the new v3 and this still an issue with the nested class it was added as CSS properties. I had to downgrade to v2.11.0 to make it run again.

**Comment by MoOx** [comment] 2017-07-06 08:15
Example of https://github.com/MoOx/postcss-cssnext/issues/389#issuecomment-312908873 in playground of v3 is not having the bug. Feel free to reopen an issue with a proper detailed example and config.

**Comment by jdinartejesus** [comment] 2017-07-06 08:25
@MoOx I'm having when using something merge class names meaning:

```
.swiper {
    &-slide {
      background-color: blue; 
   }
}
```

I'm using Webpack with the biolarplate from Vuejs and the output was:

```
.swiper {
    &-slide { background-color: blue
    };
}
```
<img width="352" alt="screen shot 2017-07-06 at 10 24 26 am" src="https://user-images.githubusercontent.com/6892132/27902253-5929dc7a-6235-11e7-8af3-ce921346988d.png">

**Comment by MoOx** [comment] 2017-07-06 08:26
per spec, it's incorrect and not supported by cssnext and postcss-nesting. Use postcss-nested for this   unofficial css notation.

**Comment by jdinartejesus** [comment] 2017-07-06 08:29
@MoOx  Then is my bad, sorry for the misunderstanding.
Btw thanks for the great work with cssnext.

Cheers
